### ISSUE TITLE
Using in Visual Studio (Missing .lib file)

### ISSUE THREAD

**Issue by kylewill0725** [troldal/OpenXLSX#11]
I'm trying to use this library in a program that is written with Visual Studio. From what I've [read](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2019#create-a-client-app-that-uses-the-dll), I need 3 things to do this: the dll file, the header files, and an import library (.lib) file. I've been able to get the dll file and header files successfully but I can't seem to get the lib file.
  
Since the Readme says that trying to compile in Windows can have issues, I set up Ubuntu 18.04 in the Windows Subsystem for Linux. Then I installed x86_64-w64-mingw32-gcc and x86_64-w64-mingw32-gcc and followed [CMake's guide to cross compiling to Windows](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/cross_compiling/Mingw). This successfully compiled the code to the dll and put all the headers in a folder.  

Am I missing something to get the lib file?

**Comment by joelpelaez** [comment]
I had the same issue. The cause is that all interface classes don't have a DLL interface when compiling with MSVC.
I tried to add these declarations, it worked in some ways but with two classes (**XLCellRange** and **XLCellReference**) it doesn't work because add `__declspec(dllexport)`. It's because a incomplete type issue with implementation classes with `std::unique_ptr`.
I can't find why it happens, strange DLL-Windows magic, but a possible solution is writing another implementation wrapper.

**Comment by r9guy** [comment]
Dear Troldal 
 I want to use the library with VC++ 2019 but this bug is not allowing to proceed further. unfortunately I have no idea how CMAKE works. Please, could you dedicate fraction of your time to fix this issue. as there will be no one to better understand what is required to do in cmake.

**Comment by joelpelaez** [comment]
I added a new pull request #12 that enable support for DLL builds in Win32 platforms. You can test it @r9guy and send me comments if you want.

**Comment by joelpelaez** [comment]
Sorry for the bad pull request. I want you review my repository https://github.com/joelpelaez/OpenXLSX and checkout the branch **add_dllexport_declspec** and compile it on Windows with VC++ 2019. The last commit I couldn't test because I have some CMake configuration issues.

If you want use the original you can change the line 4 in @library/@openxlsx/CMakeList.txt
`add_library(OpenXLSX SHARED "")`
to
`add_library(OpenXLSX STATIC "")`
or
`add_library(OpenXLSX "")`
and add to cmake command line generator options " -DBUILD_SHARED_LIBS:BOOL=OFF "

**Comment by r9guy** [comment]
@joelpelaez thanks for trying to give a solution. I have tried but it doesnt seems to help much. I have tried to compile the library by combining files in visual studio project  and have encountered that the library is implemented in 2 units, interfaces and implementation. I tried to do what was intended in original project but, in some header files there are invlude statements such as 
#include "something.h"
#include <something.h>
Apparently i think that one was intended for implementation other for interfaces sections. But i screwed up and i belive that someone more professional than me has to solve and simplyfy the code to be able then to fix CMAKE issues.

**Comment by joelpelaez** [comment]
@r9guy, you can test my repository https://github.com/joelpelaez/OpenXLSX again but now using the master branch. I merged the changes. You can build the project with the option -DSTATIC=ON and build a only .lib version.

I only wait that @troldal review and accept my pull requests to his repository.

**Comment by r9guy** [comment]
dear @joelpelaez i used your master repo straight from VS2019 . but it still doesn't compile. 
first I see that you have implemented static build as well but it doesn't show in VS2019 . 
x64 version build ends up with 
"Error	RC1110	could not open library\@openxlsx\CMakeFiles\OpenXLSX.dir/manifest.rc"

**Comment by joelpelaez** [comment]
@r9guy which command did you use to generate CMake build files? I used Ninja generator and this can't link the library. I use "Visual Studio 16 2019" generator

**Comment by joelpelaez** [comment]
@r9guy I pushed a commit that remove @ character for every folder. This allows compilation with Ninja generator, also with Visual Studio 2019 directly using open CMake project in IDE. Please can you test it and comment me about any issues?

**Comment by r9guy** [comment]
@joelpelaez  your commit worked like charm. I was able to compile without errors straight from VS 2019.
also by cloning the build configurations I was able to compile Release versions for x64 and x86 architectures. 
kindly make a pull request. 
next lets discuss how we can commit library to VCPKG package management system. but for this separate issue after merge.

**Comment by joelpelaez** [comment]
@r9guy I created the pull request with the two later pull request and the new changes. Now we need wait for @troldal response.

**Comment by joelpelaez** [comment]
@r9guy I see that you report a issue to ninja: https://github.com/ninja-build/ninja/issues/1606, but the real problem is cmake and cl.exe/link.exe.

cmake doesn't pass arguments with '@' when execute 'vs_link_dll', a build helper for DLL in Windows platforms. The reason can be because cl.exe and link.exe takes arguments starting with '@' as command files (https://docs.microsoft.com/en-us/cpp/build/reference/linking?view=vs-2019#link-command-files). This allows manage easily object files, import libraries and other arguments.

In ninja.build file the linker command used is like that:
`cmake.exe -E vs_link_dll --intdir=some_folder [other parameters] -- link.exe some.obj another.obj @this_not_work.obj /dll /out:some.dll` 
CMake helper expands arguments.txt content as arguments to link.exe command. If the file is not a text file, cmake ignores it.

Also cl.exe has the same feature, but it doesn't causea an issue because the source file path used is absolute, the '@' character is not at start and allow process as normal argument.

I didn't find a way to pass @files as normal arguments, it is why I renamed all folders, cl.exe, link.exe and cmake.exe must have a mechanism to escape '@' character.

**Comment by r9guy** [comment]
Thanks for detailed explanation. I will close the issue on ninja.

**Comment by r9guy** [comment]
I tried to build hello world with the short example on GitHub, it seems that it seems that some methods are not implemented properly. .
such as   `  auto wks = doc.Workbook()->Worksheet("Sheet1");` ->no methods are implemented in the methods. previously i have noticed that the library is using several files with the same name in in the project. perhaps we are including wrong ones? I will investigate today more and if necessary will open new ticket.

**Comment by joelpelaez** [comment]
The example is wrong, the correct one is https://gist.github.com/joelpelaez/5cab2a184684f5dc72c30068e7d182e2, It can be because the author made some changes to library interface.

**Comment by troldal** [comment]
Thanks guys for opening this issue, and thanks @joelpelaez for providing a solution. I have merged the pull request into the master. It works fine on my Mac, but I will test it on Linux and Windows when I have the time.

My apologies for the late reply; the past few months have been crazy busy, so I haven't had the time to do any work on this. I expect to be able to do more work on this in the coming months.

**Comment by troldal** [comment]
Now tested on Mac (GCC/Clang), Linux (GCC/Clang) and Windows (MinGW/Clang/MSCV). Everything appears to be working.
